-- Add to QBCore/qb-shops/config.lua
-- You may place these Foods into any Shop
-- Just make sure the "slot" # and "title" # are correct for their line

-- Foods
[1] = { -- Change to match the correct number from 0-x
    name = "sushirolls", -- Change to match the correct item
    price = 6, -- Cost in Dollars
    amount = 50, -- Stock
    info = {}, -- Usually left Blank
    type = "item", -- Item/Weapon
    slot = 1, -- Change to match the correct slot number
},
[2] = {
    name = "pizzasclice",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 2,
},
[3] = {
    name = "cookie",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 3,
},
[4] = {
    name = "muffin",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 4,
},
[5] = {
    name = "donut",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 5,
},
[6] = {
    name = "cupcake",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 6,
},
[7] = {
    name = "fries",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 7,
},
[8] = {
    name = "icecream",
    price = 5,
    amount = 50,
    info = {},
    type = "item",
    slot = 8,
},
[9] = {
    name = "gum",
    price = 2,
    amount = 50,
    info = {},
    type = "item",
    slot = 9,
},
[10] = {
    name = "ramen",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 10,
},
-- Drinks
[51] = {
    name = "icedtea",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 51,
},
[52] = {
    name = "sprite",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 52,
},
[53] = {
    name = "pepsi",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 53,
},
[54] = {
    name = "lemonade",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 54,
},
[55] = {
    name = "mtndew",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 55,
}, 
[56] = {
    name = "milk",
    price = 5,
    amount = 50,
    info = {},
    type = "item",
    slot = 56,
}, 
[57] = {
    name = "fanta",
    price = 5,
    amount = 50,
    info = {},
    type = "item",
    slot = 57,
}, 
[58] = {
    name = "drpepper",
    price = 5,
    amount = 50,
    info = {},
    type = "item",
    slot = 58,
}, 
[59] = {
    name = "pinklemonade",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 59,
},
[60] = {
    name = "fruitpunch",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 60,
},