-- Add to QBCore/qb-shops/config.lua
-- Change the numbers and the slots number as you wish or need

[12] = {
    name = "sushirolls",
    price = 6,
    amount = 50,
    info = {},
    type = "item",
    slot = 12,
},
[13] = {
    name = "pizzasclice",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 13,
},
[14] = {
    name = "cookie",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 14,
},
[15] = {
    name = "muffin",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 15,
},
[16] = {
    name = "donut",
    price = 4,
    amount = 50,
    info = {},
    type = "item",
    slot = 16,
},
[17] = {
    name = "cupcake",
    price = 3,
    amount = 50,
    info = {},
    type = "item",
    slot = 17,
},
[18] = {
    name = "icedtea",
    price = 7,
    amount = 50,
    info = {},
    type = "item",
    slot = 18,
},
[19] = {
    name = "sprite",
    price = 7,
    amount = 50,
    info = {},
    type = "item",
    slot = 19,
},
[20] = {
    name = "pepsi",
    price = 8,
    amount = 50,
    info = {},
    type = "item",
    slot = 20,
},
[21] = {
    name = "lemonade",
    price = 9,
    amount = 50,
    info = {},
    type = "item",
    slot = 21,
},
[22] = {
    name = "mtndew",
    price = 8,
    amount = 50,
    info = {},
    type = "item",
    slot = 22,
},