-- Add to QBCore/qb-core/shared.lua

-- Extra Food
    ["sushirolls"] = {
        ["name"] = "sushirolls",
        ["label"] = "sushirolls",
        ["weight"] = 400,
        ["type"] = "item",
        ["image"] = "changeme.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Sushi Roll."
    },
    ["pizzaslice"] = {
        ["name"] = "pizzaslice",
        ["label"] = "Pizza Slice",
        ["weight"] = 320,
        ["type"] = "item",
        ["image"] = "pizza-slice.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Slice of Pizza."
    },
    ["cookie"] = {
        ["name"] = "cookie",
        ["label"] = "Cookie",
        ["weight"] = 250,
        ["type"] = "item",
        ["image"] = "cookie.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Choc-Chip Cookie."
    },
    ["muffin"] = {
        ["name"] = "muffin",
        ["label"] = "Muffin",
        ["weight"] = 150,
        ["type"] = "item",
        ["image"] = "changeme.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Choc-Chip Muffin."
    },
    ["icecream"] = {
        ["name"] = "icecream",
        ["label"] = "Ice Cream",
        ["weight"] = 200,
        ["type"] = "item",
        ["image"] = "icecream.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Ice Cream."
    },
    ["fries"] = {
        ["name"] = "fries",
        ["label"] = "Fries",
        ["weight"] = 250,
        ["type"] = "item",
        ["image"] = "fries.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Some nice cold fries."
    },
    ["donut"] = {
        ["name"] = "donut",
        ["label"] = "Donut",
        ["weight"] = 200,
        ["type"] = "item",
        ["image"] = "donut.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Pink iced donut."
    },
    ["gum"] = {
        ["name"] = "gum",
        ["label"] = "Gum",
        ["weight"] = 250,
        ["type"] = "item",
        ["image"] = "gum.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Pack of Gum"
    },
    ["cupcake"] = {
        ["name"] = "cupcake",
        ["label"] = "Cupcake",
        ["weight"] = 150,
        ["type"] = "item",
        ["image"] = "cupcake.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Colorfully iced cupcake"
    },
    ["ramen"] = {
        ["name"] = "ramen",
        ["label"] = "Ramen",
        ["weight"] = 300,
        ["type"] = "item",
        ["image"] = "ramen.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Noodly Ramen"
    },

-- Extra Drinks
    ["icedtea"] = {
        ["name"] = "icedtea",
        ["label"] = "Iced Tea",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = "icedtea.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Iced Brew of Tea"
    },
    ["sprite"] = {
        ["name"] = "sprite",
        ["label"] = "Sprite",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = ".png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Sprite more like Light"
    },
    ["pepsi"] = {
        ["name"] = "pepsi",
        ["label"] = "Pepsi",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = ".png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Knock off CocaCola"
    },
    ["lemonade"] = {
        ["name"] = "lemonade",
        ["label"] = "Lemonade",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = "lemonade.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Straight from the Juice"
    },
    ["pinklemonade"] = {
        ["name"] = "pinklemonade",
        ["label"] = "Pink Lemonade",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = ".png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Straight from the Pink Juice"
    },
    ["mtndew"] = {
        ["name"] = "mtndew",
        ["label"] = "Mountain Dew",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = ".png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Drink that may cause your genitals to get smaller."
    },
    ["milk"] = {
        ["name"] = "milk",
        ["label"] = "Milk",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = "milk.png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Drink of Cow Produce"
    },
    ["fanta"] = {
        ["name"] = "fanta",
        ["label"] = "Fanta",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = ".png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Drink of Orange SuperPowers"
    },
    ["drpepper"] = {
        ["name"] = "drpepper",
        ["label"] = "Dr. Pepper",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = ".png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Drink of the Doctors Finest"
    },
    ["fruitpunch"] = {
        ["name"] = "fruitpunch",
        ["label"] = "Fruit Punch",
        ["weight"] = 100,
        ["type"] = "item",
        ["image"] = ".png",
        ["unique"] = false,
        ["useable"] = true,
        ["shouldClose"] = true,
        ["combinable"] = nil,
        ["description"] = "Drink that Smiles Back"
    },